# ansible N1 -m file -a "path=/home/centos/N1_dir state=directory"
---
- name: Update N1 servers
  hosts: N1
  remote_user: root

  tasks:
  - name: Create Directory 
    file:
      path: /home/centos/new_dir
      state: directory
...
